spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/VTBMarket
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        types:
          print:
            banner: false
